name: Lint

on:
  push:
    branches: [lint]
  pull_request:
    branches: [lint]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4 # retrieve the repo
        with:
          fetch-depth: 0

      - name: Run Super-Linter
        uses: super-linter/super-linter@v6
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_JAVASCRIPT_ES: true
          VALIDATE_HTML: true
          VALIDATE_CSS: true
          VALIDATE_PHP: true
